version: 1.0.{build}
image: Visual Studio 2017
environment:
  matrix:
  - TEST_PROJECT: arm-analysisservices
  - TEST_PROJECT: arm-authorization
install:
- ps: .\install.ps1
build_script:
- ps: .\build.ps1
test_script:
- ps: .\Test.ps1